#!/bin/bash

# Put this in /usr/local/bin or ~/bin, and run "unspadify install" to set up.
# Or "unspadify install /tmp/unspadify.log" for debugging.

PLIST=$HOME/Library/LaunchAgents/unspadify.plist
LOGFILE="$2"
APPLICATION=$(echo U3BvdGlmeQo= | base64 --decode) # obfuscation

function _usage() {
  echo "Usage: $0 <install|uninstall|run> [logfilename]"
  exit 1
}

function _log() {
  [ "$LOGFILE" ] || return
  echo "$(date): $*" >> $LOGFILE
}

function _uninstall() {
  echo "Unloading and removing file"
  launchctl unload $PLIST
  mv -f -v $PLIST /tmp
}

function _install() {
  [ -f "$PLIST" ] && _uninstall
  echo "Installing $PLIST and loading"
  cat > $PLIST <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>unspadify</string>
    <key>ProgramArguments</key>
    <array>
$( for ARG in $0 run $LOGFILE; do echo "        <string>$ARG</string>"; done)
    </array>
    <key>WatchPaths</key>
    <array>
$(
  find "$HOME/Library/Application Support/$APPLICATION/Users" -name ad-state-storage.bnk | \
    while read ADFILE; do echo "        <string>$ADFILE</string>"; done
)
    </array>
</dict>
</plist>
EOF
  launchctl load $PLIST
  echo 'Hit "OK" when prompted for permission'
}

function _tell_app() {
  osascript -e "tell application \"$APPLICATION\"
    $1
  end tell"
}

function _get_track() {
  _tell_app "set c to the current track
    set x to the $1 of c as text"
}

function _run() {
  _log "checking player state"
  if _tell_app 'player state' | grep -q 'playing'
  then
    IS_MUTED=$(osascript -e 'output muted of (get volume settings)')
    # the files change like 3 seconds before the switch, do multiple checks
    for ATTEMPT in $(seq 12)
    do
      IS_AD=$(_get_track 'id' | grep -q ':ad:' && echo true || echo false)
      if [ "$IS_AD" != "$IS_MUTED" ]
      then
        _log "muting $IS_AD on cycle $ATTEMPT"
        osascript -e "set volume output muted $IS_AD"
        break # end the for loop
      fi
      sleep 0.5
    done
  fi
}

case "$1" in
  i*) _install ;;
  u*) _uninstall ;;
  r*) _run ;;
  *)  _usage ;;
esac

